# Generated by Django 3.1 on 2020-09-28 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('desc', models.CharField(max_length=100, verbose_name='文章简介')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('up_num', models.BigIntegerField(verbose_name='点赞数')),
                ('down_num', models.BigIntegerField(verbose_name='点踩数')),
                ('comment_num', models.BigIntegerField(verbose_name='评论数')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='站点名称')),
                ('title', models.CharField(max_length=100, verbose_name='站点标题')),
                ('theme', models.CharField(max_length=64, verbose_name='个人站点样式')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='avatar/default.jpg', upload_to='avatar/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.CreateModel(
            name='Updown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField(verbose_name='是否是点赞')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.site')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.article')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.site')),
            ],
        ),
        migrations.CreateModel(
            name='Article2Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.article')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.label')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bbs.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='labels',
            field=models.ManyToManyField(through='bbs.Article2Label', to='bbs.Label'),
        ),
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bbs.site'),
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bbs.site'),
        ),
    ]
