# Generated by Django 3.1 on 2020-09-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20200929_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='static/img/avatar/default.jpg', upload_to='static/img/avatar/', verbose_name='头像'),
        ),
    ]
