# Generated by Django 3.1 on 2020-08-08 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Author_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BigIntegerField(verbose_name='手机号')),
                ('addr', models.CharField(max_length=50, verbose_name='住址')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='出版社名称')),
                ('addr', models.CharField(max_length=20, verbose_name='所在地')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('authors', models.ManyToManyField(to='bookmanage.Author')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanage.publish')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookmanage.author_detail'),
        ),
    ]
