# Generated by Django 3.1 on 2020-08-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pid',
            new_name='publish',
        ),
    ]
