# Generated by Django 3.1 on 2020-09-05 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0003_auto_20200808_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisTime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
