# Generated by Django 3.1 on 2020-09-05 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0004_book_publistime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisTime',
            new_name='publishTime',
        ),
    ]
