# Generated by Django 3.1 on 2020-09-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0005_auto_20200905_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_detail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
