# Generated by Django 3.1 on 2020-09-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0006_author_detail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kucun',
            field=models.IntegerField(default=1000, verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='book',
            name='maichu',
            field=models.IntegerField(default=1000, verbose_name='卖出'),
        ),
    ]
